name: 漏洞汇报（简体中文）
description: 提交Modern Font Pack - Caxton Edition漏洞汇报
title: "[Bug] "
labels: ["Bug", "Pending"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您抽出宝贵时间填写此漏洞汇报！
  - type: textarea
    id: what-happened
    attributes:
      label: 漏洞描述
      description: 请详细描述发生的漏洞信息。
      placeholder: 告诉我们发生了什么漏洞。
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: 重现步骤
      description: 请描述触发漏洞的步骤。
      placeholder: |
        1. ...
        2. ...
        3. ...
      render: bash
    validations:
      required: true
  - type: input
    id: expected-behavior
    attributes:
      label: 预期行为
      description: 请简要描述您想要的效果。
    validations:
      required: true
  - type: input
    id: actual-behavior
    attributes:
      label: 实际行为
      description: 请简要说明实际结果。
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Modern Font Pack - Caxton Edition版本
      description: 你目前使用的是什么版本的Modern Font Pack - Caxton Edition？（例如1200，可从资源包标题中的四位数字中找到。如果您使用的版本未在此处列出，则您使用的版本已过期。请更新到最新版本并尝试再次重现该漏洞。）
      options:
        - 0800
        - 0900
        - 1000
        - 1100
        - 1200
    validations:
      required: true
  - type: input
    id: game-version
    attributes:
      label: 你玩的是什么游戏版本？
      description: 请输入受影响的游戏版本。
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: 您正在使用的设备的系统是什么？
      options:
        - Windows
        - Linux
    validations:
      required: false
  - type: textarea
    id: additional-information
    attributes:
      label: 其他说明
      description: 若发生游戏崩溃，请务必在此提供游戏日志或是崩溃汇报。
      placeholder: |
        ...
      render: bash
    validations:
      required: false